temp commit
Signed-off-by: tianpingan <tianpingan2000@gmail.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -59,3 +59,19 @@ jobs:
             echo "All builds are successful/skipped"
             exit 0
           fi
+  e2e:
+    runs-on: ubuntu-latest
+    needs: [java-build, rust-build, pd-build]
+    if: ${{ always() }}
+    steps:
+      - uses: actions/checkout@v3
+      - name: Collect build result
+        run: |
+          if echo java-${{ needs.java-build.result }},rust-${{ needs.rust-build.result }},pd-${{ needs.pd-build.result }} | grep -E 'cancelled|failure' -o > null
+          then
+            echo "There are failed/cancelled builds"
+            exit 1
+          else
+            echo "All builds are successful/skipped"
+            exit 0
+          fi
